### PR TITLE
Contributed commands to get and set vscode settings

### PR DESCRIPTION
**Pull request by AndreasArvidsson**
```
test get:
    value = user.vscode_get("command-server.getSetting", "cursorless.pendingEditDecorationTime")
    print(value)

test update:
    user.vscode_with_plugin("command-server.setSetting", "cursorless.pendingEditDecorationTime", 100)
```

I suggest that we make python wrapper functions talon side for these
```
test get:
    value = user.vscode_get_setting("cursorless.pendingEditDecorationTime")
    print(value)

test update:
    user.vscode_set_setting("cursorless.pendingEditDecorationTime", 100)
```

### CODE REVIEW

**Review by pokey — COMMENTED** [review]
this feels orthogonal to the command server.  why not just add them as commands to https://github.com/AndreasArvidsson/andreas-talon-vscode?

**Comment by AndreasArvidsson** [comment]
I definitely could, but I know that you already have voice commands to update vscode settings and we can't be the only two that have need of this feature. If you don't think that this feature belongs in the command server I will just move it to my own extension.

**Comment by pokey** [comment]
yeah i'm just concerned with this repo becoming a dumping ground for all kinds of commands that are useful for voice coding.  trying to keep it focused on communication.  I'd be inclined to use your repo for now, and then if we want we can think about factoring some pieces of your repo out into a more generally useful core that we add as a dependency of https://marketplace.visualstudio.com/items?itemName=pokey.talon.  but for the time being i don't see a problem in just having people install your repo

**Comment by AndreasArvidsson** [comment]
Okay sounds fine to me.

**Pull request closed without merging**
